version: '3'
services:
  php:
    container_name: php
    build:
      context: ./
    ports:
      - ${PHP_HOST_PORT}:${PHP_CONTAINER_PORT}
    volumes:
      - ./:/var/www/html

  nginx:
    container_name: nginx
    build:
      context: ./
      dockerfile: Dockerfile_NGINX
    ports:
      - ${NGINX_HOST_PORT}:${NGINX_CONTAINER_PORT}
    depends_on:
      - php
    volumes:
      - ./:/var/www/html
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
